name: checks
on:
  - push
  - pull_request

jobs:
  test:
    uses: tbrul/.github/.github/workflows/node_test.yml@main
    with:
      disable-windows: true

  lint:
    uses: tbrul/.github/.github/workflows/node_lint.yml@main

  typecheck:
    uses: tbrul/.github/.github/workflows/node_typecheck.yml@main
